// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/favicon.png"
  ]
};

// ../../../../../opt/homebrew/Cellar/cloudflare-wrangler2/3.28.1/libexec/lib/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/vigneshks/Documents/GitHub/d1-lucia/.wrangler/tmp/pages-P4esJS/bundledWorker-0.9971510859186363.mjs";
import { isRoutingRuleMatch } from "/opt/homebrew/Cellar/cloudflare-wrangler2/3.28.1/libexec/lib/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/vigneshks/Documents/GitHub/d1-lucia/.wrangler/tmp/pages-P4esJS/bundledWorker-0.9971510859186363.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        if (worker.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return worker.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=jqb86a0vj6.js.map
